import Link from 'next/link';
import { getT } from '@/lib/i18n';

export const dynamic = 'force-dynamic';

const TONE: Record<string, string> = {
  Real: 'bg-go-soft text-go',
  'Rebuilt here': 'bg-go-soft text-go',
  Mocked: 'bg-ink-50 text-ink-500',
  Synthetic: 'bg-ink-50 text-ink-500',
  Estimated: 'bg-wait-soft text-wait',
  'Not built': 'bg-ink-50 text-ink-500',
};

const ROWS = [
  ['DigiLocker', 'Rebuilt here', 'A working rebuild with synthetic documents. The consent screen, issuers, fetch and returned fields follow the real shape, and the signature is an HMAC with a demo key — not a government certificate chain. It is not DigiLocker, is not connected to DigiLocker, and no document it returns exists outside this project.'],
  ['UMANG face authentication', 'Rebuilt here', 'The activation flow is rebuilt so the step can be finished rather than described. No camera is used, no face is captured, and nothing is matched against Aadhaar.'],
  ['EPFO member portal screens', 'Rebuilt here', 'Field for field, label for label, from the real portal. Every substituted field carries a note. Pressing submit updates your case in our database and nothing else.'],
  ['Employer portal and the shared link', 'Rebuilt here', 'Members cannot see the real employer portal, so we built what the task needs instead: a queue of requests waiting on one establishment. The link is signed and carries no case identifier. Approving a request updates the member’s case here. Nothing reaches a real employer or EPFO record.'],
  ['EPFO APIs', 'Mocked', 'There is no public API for any of this. Nothing in this project makes a request to an EPFO system.'],
  ['Filing a claim, and settlement', 'Not built', 'You cannot file from here, by design. Seven Gates stops at the moment before filing: when you do file on EPFO’s own portal, none of the seven things that get claims refused are still wrong.'],
  ['Aadhaar / UIDAI verification', 'Mocked', 'No Aadhaar authentication of any kind. No real Aadhaar number exists anywhere in this project; every one is deliberately invalid and masked on screen.'],
  ['Bank account verification', 'Mocked', 'No penny-drop, no IFSC lookup. The IFSC codes here belong to no bank.'],
  ['Sign-up, captcha and OTP', 'Mocked', 'No SMS is sent. The OTP is fixed and printed on screen. Demo accounts carry their password on the card.'],
  ['Documents', 'Synthetic', 'Every document is generated from a template, watermarked, and carries deliberately invalid identifiers. None is a copy of a real document.'],
  ['Member records', 'Synthetic', 'Six demo members cover six real failure patterns. No real person’s data is used anywhere, including seed data and repository fixtures.'],
  ['Settlement timings', 'Estimated', 'Held in one config file, with a source, last-checked date, and whether it is published, reported, or our estimate. They are estimates, not guarantees.'],
  ['The gate logic', 'Real', 'The dependency graph, topological ordering, critical path and day count are genuinely computed from the spec, unit-tested, and not staged for the demo.'],
  ['Case persistence', 'Real', 'Your progress is written to Postgres and survives a refresh, a closed tab, and coming back days later at the same link.'],
  ['Translation into Hindi and Kannada', 'Estimated', 'Translations were generated by a machine translation workflow and have not yet been reviewed line by line by a fluent speaker. Treat this row as a limitation, not a quality claim.'],
  ['The assistant, and speech', 'Real', 'Groq supplies assistant replies and Sarvam supplies speaking and listening. Your question and case state are sent to them. The assistant can only see the case in your browser cookie.'],
  ['Rate limiting', 'Real', 'Genuinely enforced, but held in memory, so it resets on deployment and is not shared across serverless instances. Adequate for a demo, not production.'],
] as const;

const SOURCES = [
  ['About a quarter of claims refused — 26% in FY 2023-24', 'Factly / Dataful’s analysis of EPFO claim data. Their five-year average is close to 27%; this is the broad measure across every claim type.'],
  ['Final settlements specifically: from about 13% to about 34%', 'An Indian Express analysis of EPFO data covering FY 2017-18 to FY 2022-23. This narrower measure counts final settlement after leaving a job.'],
  ['EPFO says the rate is falling', 'EPFO told the New Indian Express in December 2024 that rejections were down to 25% through November of FY 2024-25. We have not found a published full-year FY25 figure.'],
  ['A clean, fully KYC-linked claim settles in about three working days', 'EPFO’s auto-settlement route, with the ceiling raised to Rs 5 lakh in June 2025. This is the baseline the countdown uses.'],
  ['An Aadhaar-verified member can file the Joint Declaration through DigiLocker', 'EPFO publishes no turnaround for it, so the five-day figure in our gate spec is labelled as our own estimate.'],
  ['Every other latency in the product', 'Each carries its source, last-checked date, and whether it is published, reported or estimated.'],
] as const;

export default async function WhatsMockedPage() {
  const t = await getT();
  return (
    <main className="mx-auto w-full max-w-[1000px] px-5 pb-28 pt-12">
      <p className="text-[12px] font-bold uppercase tracking-[0.14em] text-teal-600">{t('Transparency')}</p>
      <h1 className="mt-2 max-w-[22ch] text-[36px] leading-[1.1] font-bold tracking-tight text-ink-900">{t("What's real and what's mocked")}</h1>
      <p className="mt-5 max-w-[72ch] text-[17px] leading-relaxed text-ink-700">{t('This page is linked from every other page rather than buried at the bottom of one, because a tool that talks about identity documents and provident fund money should be unambiguous about what it touches and what it only pretends to. Everything below is either something we genuinely built, something we rebuilt as a working stand-in, or something we did not build at all — and it says which.')}</p>

      <div className="mt-8 rounded-lg border-2 border-teal-100 bg-teal-50 p-5">
        <h2 className="text-[18px] font-bold text-teal-900">{t('You never have to upload anything')}</h2>
        <p className="mt-2 text-[15px] leading-relaxed text-teal-900">{t('There is no file upload in Seven Gates. Documents arrive through the rebuilt DigiLocker, already structured, which means nothing has to be read off a photograph and no document of yours ever leaves your own device. That was a deliberate choice, and the reason for it is at the bottom of this page.')}</p>
      </div>

      <section className="mt-10 overflow-hidden rounded-lg border border-ink-100">
        {ROWS.map(([thing, state, detail], i) => <article key={thing} className={`grid gap-3 px-5 py-4 sm:grid-cols-[1fr_auto] sm:items-start ${i ? 'border-t border-ink-100' : ''}`}><div><h2 className="text-[16px] font-bold text-ink-900">{t(thing)}</h2><p className="mt-1 text-[15px] leading-relaxed text-ink-700">{t(detail)}</p></div><span className={`justify-self-start rounded-full px-3 py-1 text-[12px] font-bold sm:justify-self-end ${TONE[state]}`}>{t(state)}</span></article>)}
      </section>

      <section className="mt-14"><h2 className="text-[26px] font-bold tracking-tight text-ink-900">{t('Where the numbers come from')}</h2><div className="mt-5 space-y-3">{SOURCES.map(([title, detail]) => <article key={title} className="rounded-lg border border-ink-100 bg-white p-5"><h3 className="text-[16px] font-bold text-ink-900">{t(title)}</h3><p className="mt-1.5 text-[15px] leading-relaxed text-ink-700">{t(detail)}</p></article>)}</div></section>

      <section className="mt-14 space-y-5"><h2 className="text-[26px] font-bold tracking-tight text-ink-900">{t('Limitations worth naming')}</h2>{[['Reading Indic scripts is not reliable enough to trust silently', 'In our own testing, a vision model read a Kannada passbook name as a different surname entirely while reading the account number perfectly. That is why documents now arrive through DigiLocker as structured fields, and why image text must be confirmed before comparison.'], ['A demo is not a deployment', 'Six members, one database, no real load. Rate limiting resets on deploy. Nothing here has been tested against the scale and inconsistency of real government systems.'], ['We are not EPFO, and this is not advice', 'An independent prototype built for a hackathon. Not affiliated with, endorsed by, or connected to EPFO or any government body. Check EPFO’s own portal before you act.']].map(([title, detail]) => <article key={title} className="rounded-lg border-l-4 border-teal-700 bg-teal-50 px-5 py-4"><h3 className="text-[17px] font-bold text-teal-900">{t(title)}</h3><p className="mt-1.5 text-[15px] leading-relaxed text-teal-900">{t(detail)}</p></article>)}</section>

      <section className="mt-14 rounded-lg border border-ink-100 bg-white p-6"><h2 className="text-[20px] font-bold text-ink-900">{t("EPFO's side of it")}</h2><p className="mt-2 text-[15px] leading-relaxed text-ink-700">{t('EPFO points to 5.08 crore claims settled in FY 2024-25, an auto-settlement route that now covers claims up to Rs 5 lakh, and refusal rates it says are falling. That is the baseline this product measures against — not a claim that EPFO is standing still.')}</p><p className="mt-5 border-t border-ink-100 pt-5 text-[15px] leading-relaxed text-ink-700">{t('Everything said here about EPFO’s screens, labels and links was seen by browsing the public portal by hand, in an ordinary browser session. No automated access, scripted requests, load testing, or live claim was involved.')}</p></section>

      <div className="mt-10 flex flex-wrap gap-3"><Link href="/compare" className="rounded-md bg-teal-700 px-5 py-3 text-[15px] font-bold text-white hover:bg-teal-600">{t('What we checked about EPFO')}</Link><Link href="/" className="rounded-md border-2 border-ink-100 px-5 py-3 text-[15px] font-semibold text-ink-700 hover:border-teal-700 hover:text-teal-700">{t('Back to the start')}</Link></div>
    </main>
  );
}
