import Link from 'next/link';
import { getT } from '@/lib/i18n';

export const dynamic = 'force-dynamic';

const TONE: Record<string, string> = {
  Real: 'bg-go-soft text-go',
  'Rebuilt here': 'bg-go-soft text-go',
  Mocked: 'bg-ink-50 text-ink-500',
  Synthetic: 'bg-ink-50 text-ink-500',
  Estimated: 'bg-wait-soft text-wait',
  'Not built': 'bg-ink-50 text-ink-500',
};

const ROWS = [
  ['DigiLocker', 'Rebuilt here', 'A working stand-in with made-up documents. The screens and returned fields follow the real flow. It uses a demo HMAC key, not a government certificate. It is not connected to DigiLocker.'],
  ['UMANG face authentication', 'Rebuilt here', 'The activation flow is rebuilt so the step can be finished rather than described. No camera is used, no face is captured, and nothing is matched against Aadhaar.'],
  ['EPFO member portal screens', 'Rebuilt here', 'Field for field, label for label, from the real portal. Every substituted field carries a note. Pressing submit updates your case in our database and nothing else.'],
  ['Employer portal and the shared link', 'Rebuilt here', 'Members cannot see the real employer portal, so we built what the task needs instead: a queue of requests waiting on one establishment. The link is signed and carries no case identifier. Approving a request updates the member’s case here. Nothing reaches a real employer or EPFO record.'],
  ['EPFO APIs', 'Mocked', 'There is no public API for any of this. Nothing in this project makes a request to an EPFO system.'],
  ['Filing a claim, and settlement', 'Not built', 'You cannot file from here, by design. Seven Gates stops at the moment before filing: when you do file on EPFO’s own portal, none of the seven things that get claims refused are still wrong.'],
  ['Aadhaar / UIDAI verification', 'Mocked', 'No Aadhaar authentication of any kind. No real Aadhaar number exists anywhere in this project; every one is deliberately invalid and masked on screen.'],
  ['Bank account verification', 'Mocked', 'No penny-drop, no IFSC lookup. The IFSC codes here belong to no bank.'],
  ['Sign-up, captcha and OTP', 'Mocked', 'No SMS is sent. The OTP is fixed and printed on screen. Demo accounts carry their password on the card.'],
  ['Documents', 'Synthetic', 'Every document is generated from a template, watermarked, and carries deliberately invalid identifiers. None is a copy of a real document.'],
  ['Member records', 'Synthetic', 'Six demo members cover six real failure patterns. No real person’s data is used anywhere, including seed data and repository fixtures.'],
  ['Settlement timings', 'Estimated', 'Held in one config file, with a source, last-checked date, and whether it is published, reported, or our estimate. They are estimates, not guarantees.'],
  ['The gate logic', 'Real', 'The dependency graph, topological ordering, critical path and day count are genuinely computed from the spec, unit-tested, and not staged for the demo.'],
  ['Case persistence', 'Real', 'Your progress is written to Postgres and survives a refresh, a closed tab, and coming back days later at the same link.'],
  ['Translation into Hindi and Kannada', 'Estimated', 'Translations were generated by a machine translation workflow and have not yet been reviewed line by line by a fluent speaker. Treat this row as a limitation, not a quality claim.'],
  ['The assistant, and speech', 'Real', 'Groq supplies assistant replies and Sarvam supplies speaking and listening. Your question and case state are sent to them. The assistant can only see the case in your browser cookie.'],
  ['Rate limiting', 'Real', 'Genuinely enforced, but held in memory, so it resets on deployment and is not shared across serverless instances. Adequate for a demo, not production.'],
] as const;

const TECHNOLOGY = [
  ['A small, boring stack that stays understandable', 'Next.js and TypeScript keep the interface, routes and server actions in one strongly typed codebase. Tailwind gives us a consistent, responsive UI without a separate design system to keep in sync.'],
  ['A real backend boundary', 'Postgres is the source of truth for cases, progress and chat history. Server-side cookies scope every case lookup, and the assistant API validates input, limits requests and never trusts a client-provided case id.'],
  ['Rules, not model guesses', 'The seven-gate resolver is a pure, unit-tested function: facts go in and an ordered critical path comes out. That makes the core result deterministic, inspectable and safe to improve independently of the language model.'],
  ['Proof of concept, ready to grow', 'Today this is a focused hackathon deployment with a small connection pool and in-memory rate limits. For real traffic we would move limits to shared storage, put Postgres behind a managed pooler, add queues for slow work, cache public configuration, and scale stateless Next.js instances horizontally.'],
  ['Designed for the next order of magnitude', 'The app already keeps business logic in data modules, isolates third-party calls behind API routes, and avoids putting secrets or personal case data in the browser. Those seams let us add observability, retries, background jobs and regional capacity without rewriting the product.'],
] as const;

const SOURCES = [
  ['About a quarter of claims refused — 26% in FY 2023-24', 'Factly / Dataful’s analysis of EPFO claim data. Their five-year average is close to 27%; this is the broad measure across every claim type.'],
  ['Final settlements specifically: from about 13% to about 34%', 'An Indian Express analysis of EPFO data covering FY 2017-18 to FY 2022-23. This narrower measure counts final settlement after leaving a job.'],
  ['EPFO says the rate is falling', 'EPFO told the New Indian Express in December 2024 that rejections were down to 25% through November of FY 2024-25. We have not found a published full-year FY25 figure.'],
  ['A clean, fully KYC-linked claim settles in about three working days', 'EPFO’s auto-settlement route, with the ceiling raised to Rs 5 lakh in June 2025. This is the baseline the countdown uses.'],
  ['An Aadhaar-verified member can file the Joint Declaration through DigiLocker', 'EPFO publishes no turnaround for it, so the five-day figure in our gate spec is labelled as our own estimate.'],
  ['Every other latency in the product', 'Each carries its source, last-checked date, and whether it is published, reported or estimated.'],
] as const;

export default async function WhatsMockedPage() {
  const t = await getT();
  return (
    <main className="mx-auto w-full max-w-[1000px] px-5 pb-28 pt-12">
      <p className="text-[12px] font-bold uppercase tracking-[0.14em] text-teal-600">{t('Transparency')}</p>
      <h1 className="mt-2 max-w-[22ch] text-[36px] leading-[1.1] font-bold tracking-tight text-ink-900">{t("What's real and what's mocked")}</h1>
      <p className="mt-5 max-w-[72ch] text-[17px] leading-relaxed text-ink-700">{t('This page tells you, in plain words, what Seven Gates really does. Some parts are real code, some are working stand-ins, and some are not built. Each section tells you which.')}</p>

      <div className="mt-8 rounded-lg border-2 border-teal-100 bg-teal-50 p-5">
        <h2 className="text-[18px] font-bold text-teal-900">{t('You never have to upload anything')}</h2>
        <p className="mt-2 text-[15px] leading-relaxed text-teal-900">{t('There is no file upload in Seven Gates. Documents arrive as structured fields through our DigiLocker stand-in. Nothing is read from a photo, and your documents never leave your device.')}</p>
      </div>

      {(['Rebuilt here', 'Real', 'Mocked', 'Synthetic', 'Estimated', 'Not built'] as const).map((state) => {
        const rows = ROWS.filter((row) => row[1] === state);
        if (!rows.length) return null;
        return <section key={state} className="mt-10 overflow-hidden rounded-lg border border-ink-100"><div className="border-b border-ink-100 bg-ink-50 px-5 py-3"><h2 className="text-[20px] font-bold text-ink-900">{t(state)}</h2></div>{rows.map(([thing, , detail], i) => <article key={thing} className={`grid gap-3 px-5 py-4 sm:grid-cols-[1fr_auto] sm:items-start ${i ? 'border-t border-ink-100' : ''}`}><div><h3 className="text-[16px] font-bold text-ink-900">{t(thing)}</h3><p className="mt-1 text-[15px] leading-relaxed text-ink-700">{t(detail)}</p></div><span className={`justify-self-start rounded-full px-3 py-1 text-[12px] font-bold sm:justify-self-end ${TONE[state]}`}>{t(state)}</span></article>)}</section>;
      })}

      <section className="mt-14"><h2 className="text-[26px] font-bold tracking-tight text-ink-900">{t('Where the numbers come from')}</h2><div className="mt-5 space-y-3">{SOURCES.map(([title, detail]) => <article key={title} className="rounded-lg border border-ink-100 bg-white p-5"><h3 className="text-[16px] font-bold text-ink-900">{t(title)}</h3><p className="mt-1.5 text-[15px] leading-relaxed text-ink-700">{t(detail)}</p></article>)}</div></section>

      <section className="mt-14"><h2 className="text-[26px] font-bold tracking-tight text-ink-900">{t('How we built it')}</h2><p className="mt-3 max-w-[70ch] text-[16px] leading-relaxed text-ink-700">{t('This is a proof of concept, but it is built around production-shaped boundaries: deterministic rules, a real database, server-side protection and stateless web routes.')}</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{TECHNOLOGY.map(([title, detail]) => <article key={title} className="rounded-lg border border-ink-100 bg-white p-5"><h3 className="text-[17px] font-bold text-ink-900">{t(title)}</h3><p className="mt-1.5 text-[15px] leading-relaxed text-ink-700">{t(detail)}</p></article>)}</div></section>

      <section className="mt-14 rounded-lg border border-ink-100 bg-white p-6"><h2 className="text-[20px] font-bold text-ink-900">{t("EPFO's side of it")}</h2><p className="mt-2 text-[15px] leading-relaxed text-ink-700">{t('EPFO points to 5.08 crore claims settled in FY 2024-25, an auto-settlement route that now covers claims up to Rs 5 lakh, and refusal rates it says are falling. That is the baseline this product measures against — not a claim that EPFO is standing still.')}</p><p className="mt-5 border-t border-ink-100 pt-5 text-[15px] leading-relaxed text-ink-700">{t('Everything said here about EPFO’s screens, labels and links was seen by browsing the public portal by hand, in an ordinary browser session. No automated access, scripted requests, load testing, or live claim was involved.')}</p></section>

      <div className="mt-10 flex flex-wrap gap-3"><Link href="/compare" className="rounded-md bg-teal-700 px-5 py-3 text-[15px] font-bold text-white hover:bg-teal-600">{t('What we checked about EPFO')}</Link><Link href="/" className="rounded-md border-2 border-ink-100 px-5 py-3 text-[15px] font-semibold text-ink-700 hover:border-teal-700 hover:text-teal-700">{t('Back to the start')}</Link></div>
    </main>
  );
}
