import { chromium } from 'playwright';
const B = 'http://localhost:3000';
const b = await chromium.launch();
const p = await b.newPage();
const errs = [];
p.on('console', (m) => errs.push(`[${m.type()}] ${m.text()}`));
p.on('pageerror', (e) => errs.push('PAGEERROR ' + e.message));
await p.goto(B + '/login', { waitUntil: 'networkidle' });
await p.getByRole('button', { name: /Ravi/ }).click();
await p.waitForTimeout(4000);
console.log('URL:', p.url());
console.log('--- text ---');
console.log((await p.innerText('body')).slice(0, 900));
console.log('--- console ---');
console.log(errs.slice(0, 12).join('\n'));
await b.close();
