import { chromium } from 'playwright';
const OUT = process.env.SHOT_OUT ?? '.';
const B = 'http://localhost:3000';
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2 });
const p = await ctx.newPage();
await p.goto(B + '/login', { waitUntil: 'networkidle' });
await p.getByRole('button', { name: /Ravi/ }).click();
await p.waitForURL('**/dashboard');
await p.waitForSelector('[data-gate]');
console.log('url:', p.url().replace(B, ''));
console.log('header links:', (await p.locator('header a, header button').allInnerTexts()).join(' | '));
console.log('sidebar visible on mobile:', await p.locator('aside').isVisible());
console.log('overflow:', await p.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth));
await p.screenshot({ path: `${OUT}/w-mobile-final.png` });
await b.close();
